create table if not exists public.leads (
  id             uuid        primary key default gen_random_uuid(),
  owner_id       uuid        not null references auth.users(id) on delete cascade,
  pipeline_id    uuid        not null references public.pipelines(id) on delete cascade,
  column_id      uuid        references public.pipeline_columns(id) on delete set null,
  deal_number    integer,
  name           text        not null,
  company        text,
  whatsapp       text,
  phone_ddi      text,
  site           text,
  email          text,
  value          numeric     not null default 0,
  responsible    text,
  priority       text        not null default 'Média',
  origin         text        not null default 'Outro',
  product_id     text,
  status         text        not null default 'open',
  tags           text[]      not null default '{}',
  notes          text        not null default '',
  entry_date     date        not null default current_date,
  next_follow_up date,
  position       integer     not null default 0,
  document       text,
  birth_date     date,
  country        text        default 'Brasil',
  zip_code       text,
  address        text,
  addr_number    text,
  complement     text,
  neighborhood   text,
  city           text,
  state          text,
  created_at     timestamptz not null default now()
);

alter table public.leads enable row level security;
